export const GET_DEFAULT_NEWS = "GET_DEFAULT_NEWS";
export const SET_DEFAULT_NEWS = "SET_DEFAULT_NEWS";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const GET_ARTICLE_BY_ID = "GET_ARTICLE_BY_ID";
export const SET_ARTICLE_BY_ID = "SET_ARTICLE_BY_ID";
export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";